// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClj-es8XBQP2uihwdLDZEzTaNey1DlI10',
    appId: '1:17146362117:web:7028320792c6fe3e351f6c',
    messagingSenderId: '17146362117',
    projectId: 'hksena-b7dad',
    authDomain: 'hksena-b7dad.firebaseapp.com',
    storageBucket: 'hksena-b7dad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh8UPKlaqt0p3p8lHuAa1BCvCR-7aPCaI',
    appId: '1:17146362117:android:5ebab44f26ec94fc351f6c',
    messagingSenderId: '17146362117',
    projectId: 'hksena-b7dad',
    storageBucket: 'hksena-b7dad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGAPzDXos8ir7a-kYQnn9L_01ATugvnXY',
    appId: '1:17146362117:ios:e6a4c64efffe5293351f6c',
    messagingSenderId: '17146362117',
    projectId: 'hksena-b7dad',
    storageBucket: 'hksena-b7dad.appspot.com',
    iosBundleId: 'com.majlis.hksena',
  );
}
